INSERT INTO MOVIES(ID,TITLE,RELEASE_YEAR) VALUES(1, 'Bagrangi Bhaijaan',2015);
INSERT INTO MOVIES(ID,TITLE,RELEASE_YEAR) VALUES(2, '3 Idiots',2010);
INSERT INTO MOVIES(ID,TITLE,RELEASE_YEAR) VALUES(3, 'Munna Bhai M B B S',2005);
INSERT INTO MOVIES(ID,TITLE,RELEASE_YEAR) VALUES(4, 'Dirty Picture',2012);
